// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKGJxvi3Wkpu4aFH1N64pfpzNj5c0_gKE',
    appId: '1:920402417962:web:ee74d97f0690e928e52653',
    messagingSenderId: '920402417962',
    projectId: 'e-commerce-app-e7fd2',
    authDomain: 'e-commerce-app-e7fd2.firebaseapp.com',
    storageBucket: 'e-commerce-app-e7fd2.appspot.com',
    measurementId: 'G-SFY8SB626Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd34Q2YCAZMEKFhLPgo4Y_DfccmSPYRog',
    appId: '1:920402417962:android:b8c9a68a49cc8cfbe52653',
    messagingSenderId: '920402417962',
    projectId: 'e-commerce-app-e7fd2',
    storageBucket: 'e-commerce-app-e7fd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI3xe1W8Lt0U50r5Qlrjpeh0-G93xTBag',
    appId: '1:920402417962:ios:f410b7fcc6f6c7f3e52653',
    messagingSenderId: '920402417962',
    projectId: 'e-commerce-app-e7fd2',
    storageBucket: 'e-commerce-app-e7fd2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI3xe1W8Lt0U50r5Qlrjpeh0-G93xTBag',
    appId: '1:920402417962:ios:4fe886f5ffbb7691e52653',
    messagingSenderId: '920402417962',
    projectId: 'e-commerce-app-e7fd2',
    storageBucket: 'e-commerce-app-e7fd2.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
